export const ROUTE_KEY = {
  PUBLIC_STACK: 'PUBLIC_STACK',
  MAIN_TAB: 'MAIN_TAB',
  HOME: 'HOME',
  SETTINGS: 'SETTINGS',
  SIGN_IN: 'SIGN_IN',
  WEB_VIEW: 'WEB_VIEW',
  PROFILE: 'PROFILE',
  SETTING_STACK: 'SETTING_STACK',
  PROFILE_DETAIL: 'PROFILE_DETAIL'
}